version: "3"
services:
  fluentd:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - python-packages:/usr/local/lib/python3.10/site-packages
      - python-bin:/usr/local/bin
volumes:
  python-packages:
  python-bin: