version: "3"
services:
  fluentd:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
volumes:
  python-packages:
  python-bin: